name: country_picker
description: A flutter package to select a country from a list of countries.

version: 2.0.15-dev.1

homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_country_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  latinize: ^0.1.0-nullsafety.0
  
flutter:
  assets:
    - lib/src/res/assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2